spring:
  config:
    import: optional:application-secrets.yml
  datasource:
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}
    driver-class_name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
